name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  pull_request:
    branches: ["main"]
    types: [labeled, unlabeled, opened, edited, synchronize]

jobs:
  Deploy-Preview:
    if: ${{ github.event.label.name == 'ready-to-dev' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      with:
        REQUIRED_LABELS_ANY: "ready-to-dev"
        REQUIRED_LABELS_ANY_DESCRIPTION: "Select at least one label ['ready-to-dev']"
        BANNED_LABELS: "banned"

      - name: Install Vercel CLI
        run: yarn global add --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Install Dependencies and Health Code
        run: yarn install && yarn lint && yarn build
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
